# 開発環境を立ち上げる。
version: "2"
services:
  db:
    container_name: wconsys-db
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=hogehoge123
      - MYSQL_DATABASE=wconsys
    ports:
      - 13306:3306
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
  web:
    container_name: wconsys-web
    build: ./docker/web/
    image: c92-example
    privileged: true
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    tty: true

