# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: kojiro526/pandoc-pack

    working_directory: ~/workspace

    steps:
      - checkout
      - run:
          apt-get install -yqq curl
      - run:
          build.sh -f -n -r ./doc/template/reference-part-2.docx -o witch-contract-design-$(dat +%H%m%d-%H%M).docx -p "--toc --toc-depth=3" ./doc/
      - run:
          curl https://slack.com/api/files.upload -F token="${SLACK_TOKEN}" -F channels="${SLACK_CHANNEL}" -F title="Document updated" -F filename="witch-contract-design.docx" -F file=@"$(pwd)/witch-contract-design.docx" -F initial_comment="https://bitbucket.org/kojiro526/witch-contract/commits/(git rev-parse HEAD) \n\n branch: $(git rev-parse --abbrev-ref HEAD)"
      - run:
          mv witch-contract-design.docx /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
